backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "source/blog/posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog_layout"}
      - {label: "Blog Name", name: "blog", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    folder: "source/page/pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layout"}
      - {label: "Blog Name", name: "blog", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "member"
    label: "Member"
    folder: "source/member/members"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layout"}
      - {label: "Blog Name", name: "blog", widget: "hidden", default: "member"}
      - {label: "Created Date", name: "date", widget: "datetime"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Personal Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
